| test.cpp:7:17:7:34 | throw ... | [AUDIT] Function $@ throws an exception of type 'ExceptionA'. | test.cpp:7:6:7:11 | throwA | throwA |
| test.cpp:9:17:9:34 | throw ... | [AUDIT] Function $@ throws an exception of type 'ExceptionB'. | test.cpp:9:6:9:11 | throwB | throwB |
| test.cpp:11:17:11:34 | throw ... | [AUDIT] Function $@ throws an exception of type 'ExceptionC'. | test.cpp:11:6:11:11 | throwC | throwC |
| test.cpp:14:3:14:8 | call to throwA | [AUDIT] Function $@ throws an exception of type 'ExceptionA'. | test.cpp:13:6:13:14 | throwBOrA | throwBOrA |
| test.cpp:15:3:15:8 | call to throwB | [AUDIT] Function $@ throws an exception of type 'ExceptionB'. | test.cpp:13:6:13:14 | throwBOrA | throwBOrA |
| test.cpp:19:3:19:11 | call to throwBOrA | [AUDIT] Function $@ throws an exception of type 'ExceptionA'. | test.cpp:18:6:18:27 | test_thrown_exceptions | test_thrown_exceptions |
| test.cpp:19:3:19:11 | call to throwBOrA | [AUDIT] Function $@ throws an exception of type 'ExceptionB'. | test.cpp:18:6:18:27 | test_thrown_exceptions | test_thrown_exceptions |
| test.cpp:20:3:20:8 | call to throwC | [AUDIT] Function $@ throws an exception of type 'ExceptionC'. | test.cpp:18:6:18:27 | test_thrown_exceptions | test_thrown_exceptions |
